services:
  database:
    image: mysql:8.0.41-debian
    volumes:
      - ./mysql-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
  backend:
    build: ./spring-backend
    restart: on-failure
    depends_on:
      - database
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - DB_HOST=database
  frontend:
    build: ./react-frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000=value
    depends_on:
      - backend
    stdin_open: true
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
volumes:
  mysql: