services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./static:/app/static
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@admin.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    depends_on:
      db:
        condition: service_healthy
    user: "djangouser"
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      retries: 5

volumes:
  pgdata:
